// <auto-generated />
using AnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelter.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    [Migration("20210122231919_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelter.Models.Cat", b =>
                {
                    b.Property<int>("CatId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("catAge")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.Property<string>("catBreed")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("catDescription")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("catGender")
                        .IsRequired()
                        .HasMaxLength(6);

                    b.Property<string>("catName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("CatId");

                    b.ToTable("Cats");

                    b.HasData(
                        new
                        {
                            CatId = 1,
                            catAge = "1 year, 5 months",
                            catBreed = "Maine Coon",
                            catDescription = "Sage is a friendly cat that really enjoys being around people. She is very loving and will give you all the cuddles you desire.",
                            catGender = "Female",
                            catName = "Sage"
                        },
                        new
                        {
                            CatId = 2,
                            catAge = "8 months",
                            catBreed = "Somali",
                            catDescription = "Appa is a fun energetic kitten that loves to play. Absolute sweetheart.",
                            catGender = "Male",
                            catName = "Appa"
                        },
                        new
                        {
                            CatId = 3,
                            catAge = "9 years, 3 months",
                            catBreed = "Domestic Shorthair",
                            catDescription = "Bailey is a sweet and gentle cat who would make an amazing companion.",
                            catGender = "Female",
                            catName = "Bailey"
                        });
                });

            modelBuilder.Entity("AnimalShelter.Models.Dog", b =>
                {
                    b.Property<int>("DogId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("dogAge")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.Property<string>("dogBreed")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("dogDescription")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("dogGender")
                        .IsRequired()
                        .HasMaxLength(6);

                    b.Property<string>("dogName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("DogId");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            DogId = 1,
                            dogAge = "2 years, 1 month",
                            dogBreed = "Great Dane",
                            dogDescription = "Joel is a sweetheart that absolutely loves to play. He is great with kids and is a perfect fit to make a family complete.",
                            dogGender = "Male",
                            dogName = "Joel"
                        },
                        new
                        {
                            DogId = 2,
                            dogAge = "4 years, 3 months",
                            dogBreed = "Pitbull, Terrier",
                            dogDescription = "Roswell is a fun energetic dog that loves to run around. He is a perfect dog to venture with and take on outdoor trips.",
                            dogGender = "Male",
                            dogName = "Roswell"
                        },
                        new
                        {
                            DogId = 3,
                            dogAge = "10 years, 3 months",
                            dogBreed = "Retriever, Labrador",
                            dogDescription = "Stone is an absolute sweetheart. She is very gentle with people and would make a perfect companion.",
                            dogGender = "Female",
                            dogName = "Stone"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
